/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMeSection: typeof import('./src/components/AboutMeSection.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    ExperienceSection: typeof import('./src/components/ExperienceSection.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    NavigationDrawer: typeof import('./src/components/navigation/NavigationDrawer.vue')['default']
    Portfolio: typeof import('./src/components/Portfolio.vue')['default']
    ProjectsSection: typeof import('./src/components/ProjectsSection.vue')['default']
  }
}
